// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {models} from '../models';

export function CreateBook(arg1:context.Context,arg2:models.Book):Promise<void>;

export function DeleteBook(arg1:context.Context,arg2:string):Promise<void>;

export function GetBookByID(arg1:context.Context,arg2:string):Promise<models.Book>;

export function GetBooks(arg1:context.Context):Promise<Array<models.Book>>;

export function UpdateBook(arg1:context.Context,arg2:string,arg3:Record<string, any>):Promise<void>;
