// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {primitive} from '../models';

export function CreateBook(arg1:models.Book):Promise<void>;

export function DeleteBook(arg1:string):Promise<void>;

export function GetBookByID(arg1:string):Promise<models.Book>;

export function GetBooks():Promise<Array<models.Book>>;

export function UpdateBook(arg1:string,arg2:primitive.M):Promise<void>;
