// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBook(arg1) {
  return window['go']['services']['BookService']['CreateBook'](arg1);
}

export function DeleteBook(arg1) {
  return window['go']['services']['BookService']['DeleteBook'](arg1);
}

export function GetBookByID(arg1) {
  return window['go']['services']['BookService']['GetBookByID'](arg1);
}

export function GetBooks() {
  return window['go']['services']['BookService']['GetBooks']();
}

export function UpdateBook(arg1, arg2) {
  return window['go']['services']['BookService']['UpdateBook'](arg1, arg2);
}
