// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBook(arg1, arg2) {
  return window['go']['services']['BookService']['CreateBook'](arg1, arg2);
}

export function DeleteBook(arg1, arg2) {
  return window['go']['services']['BookService']['DeleteBook'](arg1, arg2);
}

export function GetBookByID(arg1, arg2) {
  return window['go']['services']['BookService']['GetBookByID'](arg1, arg2);
}

export function GetBooks(arg1) {
  return window['go']['services']['BookService']['GetBooks'](arg1);
}

export function UpdateBook(arg1, arg2, arg3) {
  return window['go']['services']['BookService']['UpdateBook'](arg1, arg2, arg3);
}
