// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function DeleteAllStoragedComprobantes(arg1:Array<Record<string, any>>):Promise<void>;

export function DeleteStoragedComprobante(arg1:Record<string, any>):Promise<void>;

export function DownloadAllAvailableComprobantes():Promise<void>;

export function FetchAvailableComprobantes():Promise<Array<any>>;

export function FetchStoragedComprobantes():Promise<Array<Record<string, any>>>;

export function SelectComprobantesDownloadsDirectory():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StorageAllAvailableComprobantes(arg1:Array<Record<string, any>>):Promise<void>;

export function StorageAvailableComprobante(arg1:Record<string, any>):Promise<void>;
