// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAllStoragedComprobantes(arg1) {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['DeleteAllStoragedComprobantes'](arg1);
}

export function DeleteStoragedComprobante(arg1) {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['DeleteStoragedComprobante'](arg1);
}

export function FetchAvailableComprobantes() {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['FetchAvailableComprobantes']();
}

export function FetchStoragedComprobantes() {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['FetchStoragedComprobantes']();
}

export function SetContext(arg1) {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['SetContext'](arg1);
}

export function StorageAllAvailableComprobantes(arg1) {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['StorageAllAvailableComprobantes'](arg1);
}

export function StorageAvailableComprobante(arg1) {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['StorageAvailableComprobante'](arg1);
}
