// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {comprobante} from '../models';
import {context} from '../models';

export function DeleteAllStoragedComprobantes(arg1:Array<comprobante.Comprobante>):Promise<void>;

export function DeleteStoragedComprobante(arg1:comprobante.Comprobante):Promise<void>;

export function FetchAvailableComprobantes():Promise<Array<comprobante.Comprobante>>;

export function FetchStoragedComprobantes():Promise<Array<comprobante.Comprobante>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StorageAllAvailableComprobantes(arg1:Array<comprobante.Comprobante>):Promise<void>;

export function StorageAvailableComprobante(arg1:comprobante.Comprobante):Promise<void>;
