// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllSampleFiles() {
  return window['go']['services']['FileDownloadingService']['GetAllSampleFiles']();
}

export function SelectFilesDownloadsDirectory() {
  return window['go']['services']['FileDownloadingService']['SelectFilesDownloadsDirectory']();
}

export function SetContext(arg1) {
  return window['go']['services']['FileDownloadingService']['SetContext'](arg1);
}
