// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAllDownloads() {
  return window['go']['services']['FileDownloadingService']['CancelAllDownloads']();
}

export function CancelDownload(arg1) {
  return window['go']['services']['FileDownloadingService']['CancelDownload'](arg1);
}

export function FetchSampleFilesInformation() {
  return window['go']['services']['FileDownloadingService']['FetchSampleFilesInformation']();
}

export function GetSampleFilesStatus() {
  return window['go']['services']['FileDownloadingService']['GetSampleFilesStatus']();
}

export function PauseAllDownloads() {
  return window['go']['services']['FileDownloadingService']['PauseAllDownloads']();
}

export function PauseDownload(arg1) {
  return window['go']['services']['FileDownloadingService']['PauseDownload'](arg1);
}

export function ResumeAllDownloads() {
  return window['go']['services']['FileDownloadingService']['ResumeAllDownloads']();
}

export function ResumeDownload(arg1) {
  return window['go']['services']['FileDownloadingService']['ResumeDownload'](arg1);
}

export function SelectFilesDownloadsDirectory() {
  return window['go']['services']['FileDownloadingService']['SelectFilesDownloadsDirectory']();
}

export function SetContext(arg1) {
  return window['go']['services']['FileDownloadingService']['SetContext'](arg1);
}

export function StartAllDownloads(arg1) {
  return window['go']['services']['FileDownloadingService']['StartAllDownloads'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['services']['FileDownloadingService']['StartDownload'](arg1);
}
