// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {comprobante} from '../models';
import {context} from '../models';

export function CancelAllAvailableJsonsStoraging():Promise<void>;

export function CancelAllStoragedJsonsDeleting():Promise<void>;

export function DeleteAllStoragedJsons(arg1:Array<Record<string, any>>):Promise<void>;

export function DeleteStoragedJson(arg1:Record<string, any>):Promise<void>;

export function FetchAvailableJsons():Promise<Array<comprobante.Comprobante>>;

export function FetchStoragedJsons():Promise<Array<comprobante.Comprobante>>;

export function PauseAllAvailableJsonsStoraging():Promise<void>;

export function PauseAllStoragedJsonsDeleting():Promise<void>;

export function ResumeAllAvailableJsonsStoraging():Promise<void>;

export function ResumeAllStoragedJsonsDeleting():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StorageAllAvailableJsons(arg1:Array<Record<string, any>>):Promise<void>;

export function StorageAvailableJson(arg1:Record<string, any>):Promise<void>;
