// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAllAvailableJsonsStoraging() {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['CancelAllAvailableJsonsStoraging']();
}

export function CancelAllStoragedJsonsDeleting() {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['CancelAllStoragedJsonsDeleting']();
}

export function DeleteAllStoragedJsons(arg1) {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['DeleteAllStoragedJsons'](arg1);
}

export function DeleteStoragedJson(arg1) {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['DeleteStoragedJson'](arg1);
}

export function FetchAvailableJsons() {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['FetchAvailableJsons']();
}

export function FetchStoragedJsons() {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['FetchStoragedJsons']();
}

export function PauseAllAvailableJsonsStoraging() {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['PauseAllAvailableJsonsStoraging']();
}

export function PauseAllStoragedJsonsDeleting() {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['PauseAllStoragedJsonsDeleting']();
}

export function ResumeAllAvailableJsonsStoraging() {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['ResumeAllAvailableJsonsStoraging']();
}

export function ResumeAllStoragedJsonsDeleting() {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['ResumeAllStoragedJsonsDeleting']();
}

export function SetContext(arg1) {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['SetContext'](arg1);
}

export function StorageAllAvailableJsons(arg1) {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['StorageAllAvailableJsons'](arg1);
}

export function StorageAvailableJson(arg1) {
  return window['go']['services']['ComprobantesDataSerializerAndStoragerService']['StorageAvailableJson'](arg1);
}
