// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAllAvailableJsonsStoraging() {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['CancelAllAvailableJsonsStoraging']();
}

export function CancelAllStoragedJsonsDeleting() {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['CancelAllStoragedJsonsDeleting']();
}

export function DeleteAllStoragedJsons(arg1) {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['DeleteAllStoragedJsons'](arg1);
}

export function DeleteStoragedJson(arg1) {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['DeleteStoragedJson'](arg1);
}

export function FetchAvailableJsons() {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['FetchAvailableJsons']();
}

export function FetchStoragedJsons() {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['FetchStoragedJsons']();
}

export function PauseAllAvailableJsonsStoraging() {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['PauseAllAvailableJsonsStoraging']();
}

export function PauseAllStoragedJsonsDeleting() {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['PauseAllStoragedJsonsDeleting']();
}

export function ResumeAllAvailableJsonsStoraging() {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['ResumeAllAvailableJsonsStoraging']();
}

export function ResumeAllStoragedJsonsDeleting() {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['ResumeAllStoragedJsonsDeleting']();
}

export function SetContext(arg1) {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['SetContext'](arg1);
}

export function StorageAllAvailableJsons(arg1) {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['StorageAllAvailableJsons'](arg1);
}

export function StorageAvailableJson(arg1) {
  return window['go']['services']['JsonDataSerializerAndStoragerService']['StorageAvailableJson'](arg1);
}
