// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePost(arg1) {
  return window['go']['services']['RestService']['CreatePost'](arg1);
}

export function DeletePost(arg1) {
  return window['go']['services']['RestService']['DeletePost'](arg1);
}

export function GetPost(arg1) {
  return window['go']['services']['RestService']['GetPost'](arg1);
}

export function PatchPost(arg1, arg2) {
  return window['go']['services']['RestService']['PatchPost'](arg1, arg2);
}

export function PutPost(arg1, arg2) {
  return window['go']['services']['RestService']['PutPost'](arg1, arg2);
}
