// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePost(arg1:string):Promise<string>;

export function DeletePost(arg1:string):Promise<string>;

export function GetPost(arg1:string):Promise<string>;

export function PatchPost(arg1:string,arg2:string):Promise<string>;

export function PutPost(arg1:string,arg2:string):Promise<string>;
