// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NumberToDollars(arg1:number):Promise<string>;

export function NumberToWords(arg1:number):Promise<string>;
