// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NumberToDollars(arg1) {
  return window['go']['services']['SoapService']['NumberToDollars'](arg1);
}

export function NumberToWords(arg1) {
  return window['go']['services']['SoapService']['NumberToWords'](arg1);
}
