// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1) {
  return window['go']['services']['UserService']['CreateUser'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['services']['UserService']['DeleteUser'](arg1);
}

export function GetAllUsers() {
  return window['go']['services']['UserService']['GetAllUsers']();
}

export function GetUserByID(arg1) {
  return window['go']['services']['UserService']['GetUserByID'](arg1);
}

export function GetUserByName(arg1) {
  return window['go']['services']['UserService']['GetUserByName'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['services']['UserService']['UpdateUser'](arg1);
}
