// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {comprobante} from '../models';
import {context} from '../models';

export function CancelAllAvailableXMLsStoraging():Promise<void>;

export function DeleteStoragedXml(arg1:string):Promise<void>;

export function FetchAvailableXMLs():Promise<Array<comprobante.Comprobante>>;

export function PauseAllAvailableXMLsStoraging():Promise<void>;

export function ResumeAllAvailableXMLsStoraging():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StorageAllAvailableXMLs(arg1:Array<string>):Promise<void>;

export function StorageAvailableXml(arg1:string):Promise<void>;
