// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAllAvailableXMLsStoraging() {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['CancelAllAvailableXMLsStoraging']();
}

export function DeleteStoragedXml(arg1) {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['DeleteStoragedXml'](arg1);
}

export function FetchAvailableXMLs() {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['FetchAvailableXMLs']();
}

export function PauseAllAvailableXMLsStoraging() {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['PauseAllAvailableXMLsStoraging']();
}

export function ResumeAllAvailableXMLsStoraging() {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['ResumeAllAvailableXMLsStoraging']();
}

export function SetContext(arg1) {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['SetContext'](arg1);
}

export function StorageAllAvailableXMLs(arg1) {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['StorageAllAvailableXMLs'](arg1);
}

export function StorageAvailableXml(arg1) {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['StorageAvailableXml'](arg1);
}
