// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAllDownloads() {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['CancelAllDownloads']();
}

export function CancelDownload(arg1) {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['CancelDownload'](arg1);
}

export function PauseAllDownloads() {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['PauseAllDownloads']();
}

export function PauseDownload(arg1) {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['PauseDownload'](arg1);
}

export function ResumeAllDownloads() {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['ResumeAllDownloads']();
}

export function ResumeDownload(arg1) {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['ResumeDownload'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['SetContext'](arg1);
}

export function StartAllDownloads(arg1) {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['StartAllDownloads'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['services']['XMLDataSerializerAndStoragerService']['StartDownload'](arg1);
}
